import React, { useState } from "react";
import Head from "next/head";
import { Roboto } from "next/font/google";
import Timer from "@/components/Timer";
import Discount from "@/components/Discount";
import MyButton from "@/components/MyButton";
import MyButton2 from "@/components/MyButton2";
import MyButtonTop from "@/components/MyButtonTop";
import gen1 from "../public/img/gens/1.png";
import Image from "next/image";
import Slider from "@/components/Slider/Slider";
import SliderTitles from "@/components/Slider/SliderTitles";
import specialOfferDecorImage from "../public/img/specialOffer/1.svg";
import ReactVideo from "@/components/ReactVideo";
import mainWhyIcon1 from "../public/icons/mainWhy/1.svg";
import mainWhyIcon2 from "../public/icons/mainWhy/2.svg";
import mainWhyIcon3 from "../public/icons/mainWhy/3.svg";
import mainWhyIcon4 from "../public/icons/mainWhy/4.svg";
import genImg1 from "../public/img/gens/gensList/1.jpg";
import genImg2 from "../public/img/gens/gensList/2.jpg";
import genImg3 from "../public/img/gens/gensList/3.jpg";
import referenceIcon from "../public/icons/gensList.svg";
import referenceIconUp from "../public/icons/gensListUp.svg";
import GensList from "@/components/sections/gensList";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["100", "300", "500", "700"],
});

export default function Home() {
    const [width, setWidth] = React.useState();

    const [openLT3800, setOpenLT3800] = useState(false);
    const [openLT4500, setOpenLT4500] = useState(false);
    const [openLT6500, setOpenLT6500] = useState(false);
    React.useEffect(() => {
        function handleResize() {
            setWidth(window.innerWidth);
        }

        // Встановлюємо розмір екрану під час першого рендеру
        handleResize();

        // Додаємо слухача події на зміну розміру вікна
        window.addEventListener("resize", handleResize);

        // Прибираємо слухача події при розмонтовуванні компонента
        return () => window.removeEventListener("resize", handleResize);
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`wrapper ${roboto.className}`}>
                <section
                    className="main"
                    style={{
                        backgroundImage: "url(/img/bg/1.jpg)",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        backgroundRepeat: "no-repeat",
                    }}
                >
                    <div className="main__container">
                        <div className="main__title">
                            <MyButtonTop
                                fontSize={
                                    width < 280
                                        ? 13
                                        : width < 337
                                        ? 15
                                        : width < 430
                                        ? 17
                                        : width < 550
                                        ? 20
                                        : width < 700
                                        ? 28
                                        : width < 900
                                        ? 38
                                        : width < 1020
                                        ? 48
                                        : 55
                                }
                                fontWeight={600}
                                btnHeight="160px"
                            >
                                Бензиново-газові генератори
                            </MyButtonTop>
                        </div>
                        <div className="main__generatorImageContainer">
                            <Image
                                src={gen1}
                                className={"main__generatorImage"}
                                alt="myImg"
                            />
                        </div>
                    </div>
                </section>
                <div className="main__discount">
                    <Discount lowPrice={99999} percent={20} price={99999} />
                </div>
                <section
                    className="firstTimer"
                    style={{
                        backgroundImage: "url(/img/bg/black.png)",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        backgroundRepeat: "no-repeat",
                    }}
                >
                    <div className="firstTimer__row">
                        <div className="firstTimer__timer">
                            <Timer />
                        </div>
                        <div className="firstTimer__choseGen">
                            <MyButton2
                                fontSize={
                                    width < 400 ? 15 : width > 685 ? 42 : 25
                                }
                                fontWeight={400}
                                btnHeight="150px"
                                lineHeight={
                                    width < 400 ? 20 : width > 685 ? 50 : 25
                                }
                            >
                                Обрати потрібний <br />
                                генератор
                            </MyButton2>
                        </div>
                    </div>
                </section>
                <section className="mainSlider">
                    <div className="mainSlider__container">
                        <div className="mainSlider__title">
                            <SliderTitles />
                        </div>
                        <div className="mainSlider__row">
                            <Slider />
                        </div>
                    </div>
                </section>
                <section className="specialOffer">
                    <div className="specialOffer__title">
                        <div className="specialOffer__title-text __container">
                            СПЕЦІАЛЬНА ПРОПОЗИЦІЯ
                        </div>
                    </div>
                    <div
                        className="specialOffer__generator"
                        style={{
                            backgroundImage: "url(/img/bg/1.jpg)",
                            backgroundSize: "cover",
                            backgroundPosition: "center",
                            backgroundRepeat: "no-repeat",
                        }}
                    >
                        <div className="specialOffer__generator-img">
                            <Image src={gen1} alt="myImg" />
                        </div>
                        <div className="specialOffer__generator-decor">
                            <Image src={specialOfferDecorImage} alt="decor" />
                        </div>
                    </div>
                    <div className="specialOffer__econom">
                        <div className="specialOffer__econom-title __container">
                            ЕКОНОМІЯ 85% на пальному
                        </div>
                    </div>
                    <div className="specialOffer__text">
                        <div className="specialOffer__text-value __container">
                            Генератор <strong> Loutian LT</strong> стане
                            надійним джерелом електроенергії та забезпечить вашу
                            оселю чи офіс необхідною вам потужністю. замов
                            генератор зараз, і отримуй у подарунок газовий
                            редуктор, з яким ви зможете економити до 85% коштів
                            на паливі
                        </div>
                    </div>
                </section>
                <section
                    className="secondTimer"
                    style={{
                        backgroundImage: "url(/img/bg/black.png)",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        backgroundRepeat: "no-repeat",
                    }}
                >
                    <div className="secondTimer__row">
                        <div className="secondTimer__timer">
                            <Timer />
                        </div>
                        <div className="secondTimer__get">
                            <MyButton2
                                fontSize={
                                    width < 400 ? 15 : width > 685 ? 42 : 25
                                }
                                fontWeight={400}
                                btnHeight="150px"
                                lineHeight={
                                    width < 400 ? 20 : width > 685 ? 50 : 25
                                }
                            >
                                ОТРИМАТИ ПОДАРУНОК
                            </MyButton2>
                        </div>
                    </div>
                </section>
                <section className="mainVideo">
                    <ReactVideo
                        videoUrl={"/video/1.mp4"}
                        videoWidth={"100%"}
                        videoHeight={width < 375 ? 300 : 600}
                    />
                    <div className="mainVideo__description __container">
                        <div className="mainVideo__description-text">
                            Це бензеновий генератор, який допоможе отримати Вам
                            додаткове джерело електроенергії для використання у
                            разі проблем із електромережею з різною номінальною
                            потужністю в залежності від ваших потреб. Агрегат
                            впорається з живленням електроприладів для дому,
                            офісу
                        </div>
                    </div>
                </section>
                <section
                    className="mainWhy"
                    style={{
                        backgroundImage: "url(/img/bg/black.png)",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        backgroundRepeat: "no-repeat",
                    }}
                >
                    <div className="mainWhy__container">
                        <div className="mainWhy__row">
                            <div className="mainWhy__title1">
                                Чому вже понад 200 людей
                            </div>
                            <div className="mainWhy__title2">
                                обрали цей генератор?
                            </div>
                            <div className="mainWhy__items">
                                <div className="mainWhy__items-icon">
                                    <Image src={mainWhyIcon1} alt="icon" />
                                </div>
                                <div className="mainWhy__items-title">
                                    місткість
                                </div>
                                <div className="mainWhy__items-text">
                                    Паливного баку вистачає на 10 -15 годин без
                                    дозаправлення
                                </div>
                            </div>
                            <div className="mainWhy__dashed"></div>
                            <div className="mainWhy__items">
                                <div className="mainWhy__items-icon">
                                    <Image src={mainWhyIcon2} alt="icon" />
                                </div>
                                <div className="mainWhy__items-title">
                                    ТЕхнологічність
                                </div>
                                <div className="mainWhy__items-text">
                                    Є захист від короткого замикання та олійного
                                    голодування
                                </div>
                            </div>
                            <div className="mainWhy__dashed"></div>
                            <div className="mainWhy__items">
                                <div className="mainWhy__items-icon">
                                    <Image src={mainWhyIcon3} alt="icon" />
                                </div>
                                <div className="mainWhy__items-title">
                                    НАДІЙНИЙ
                                </div>
                                <div className="mainWhy__items-text">
                                    Регулятор напруги AVR захищає підключені
                                    пристрої
                                </div>
                            </div>
                            <div className="mainWhy__dashed"></div>
                            <div className="mainWhy__items">
                                <div className="mainWhy__items-icon">
                                    <Image src={mainWhyIcon4} alt="icon" />
                                </div>
                                <div className="mainWhy__items-title">
                                    ЕКОНОМНИЙ
                                </div>
                                <div className="mainWhy__items-text">
                                    Максимально ефективне споживання палива та
                                    масла
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="gensList">
                    <div className="gensList__item">
                        <div className="gens__title">
                            <div className="gens__title-value __container">
                                Газово-бензиновий генератор Loutian LT3800
                            </div>
                        </div>
                        <div className="gens__picture __container">
                            <Image src={genImg1} alt="generator" />
                        </div>
                        <div className="gens__discount">
                            <Discount
                                lowPrice={9999}
                                price={9999}
                                percent={20}
                            />
                        </div>
                        <div className="gens__timer">
                            <Timer />
                        </div>
                        <div className="gens__text">
                            <div className="gens__text-value __container">
                                Це бензеновий генератор, який допоможе отримати
                                Вам додаткове джерело електроенергії для
                                використання у разі проблем із електромережею з
                                різною номінальною потужністю в залежності від
                                ваших потреб. Агрегат впорається з живленням
                                електроприладів для дому, офісу
                            </div>
                        </div>
                        <div className="gens__reference">
                            <div className="gens__reference-title" onClick={()=> setOpenLT3800(!openLT3800)}>
                                <div className="gens__reference-title-value">
                                    ХАРАКТЕРИСТИКИ
                                </div>
                                <div className="gens__reference-title-icon">
                                    <Image src={!openLT3800 ? referenceIcon : referenceIconUp} alt="icon" />
                                </div>
                            </div>
                            <div className="gens__reference-row ">
                                <div
                                    className="gens__reference-row-border-first __container"
                                    style={
                                        !openLT3800
                                            ? { height: "210px" }
                                            : { height: "" }
                                    }
                                >
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система пуску:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            ручний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Номінальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            2,8 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Максимальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            3 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Напруга:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220/12 В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            бензин / газ
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Об'єм паливного бака:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            10 л.
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Витрата палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            0,7-1 л/год{" "}
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Безперебійна праця без
                                            дозаправлення:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            10-12 годин
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип двигуна:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            {" "}
                                            4-тактний Одноциліндровий с
                                            повітряним охолодженням
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Розмір циліндра:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            88 х 64 мм
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість фаз:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            однофазний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система AVR:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість розеток:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220 В: 2 шт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик рівня масла:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вольтметр:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Форм-фактор:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            пересувний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Захист від перевантаження DC/AC:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Клас ізоляції:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вага:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            38кг
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="gens__buy">
                            <MyButton2
                                btnHeight="140px"
                                fontSize={
                                    width < 312 ? 15 : width > 505 ? 30 : 18
                                }
                                lineHeight={width > 505 ? 40 : 20}
                            >
                                Замовити зі знижкою
                                <br />
                                LUOTIAN LT3800
                            </MyButton2>
                        </div>
                    </div>
                    <div className="gensList__item">
                        <div className="gens__title">
                            <div className="gens__title-value __container">
                                Газово-бензиновий генератор LUOTIAN LT4500
                            </div>
                        </div>
                        <div className="gens__picture __container">
                            <Image src={genImg2} alt="generator" />
                        </div>
                        <div className="gens__discount">
                            <Discount
                                lowPrice={9999}
                                price={9999}
                                percent={20}
                            />
                        </div>
                        <div className="gens__timer">
                            <Timer />
                        </div>
                        <div className="gens__text">
                            <div className="gens__text-value __container">
                                Це бензеновий генератор, який допоможе отримати
                                Вам додаткове джерело електроенергії для
                                використання у разі проблем із електромережею з
                                різною номінальною потужністю в залежності від
                                ваших потреб. Агрегат впорається з живленням
                                електроприладів для дому, офісу
                            </div>
                        </div>
                        <div className="gens__reference">
                            <div className="gens__reference-title" onClick={()=> setOpenLT4500(!openLT4500)}>
                                <div className="gens__reference-title-value">
                                    ХАРАКТЕРИСТИКИ
                                </div>
                                <div className="gens__reference-title-icon">
                                    <Image src={!openLT4500 ? referenceIcon : referenceIconUp} alt="icon" />
                                </div>
                            </div>
                            <div className="gens__reference-row ">
                                <div
                                    className="gens__reference-row-border-second __container"
                                    style={
                                        !openLT4500
                                            ? { height: "210px" }
                                            : { height: "" }
                                    }
                                >
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система пуску:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            ручний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Номінальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            4 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Максимальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            4,5 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Напруга:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220/12 В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            бензин / газ
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Об'єм паливного бака:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            15 л.
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Витрата палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            0,7-1 л/год{" "}
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Безперебійна праця без
                                            дозаправлення:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            15-20 годин
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип двигуна:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            {" "}
                                            4-тактний Одноциліндровий с
                                            повітряним охолодженням
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Розмір циліндра:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            88 х 64 мм
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість фаз:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            однофазний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система AVR:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість розеток:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220 В: 2 шт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик рівня масла:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вольтметр:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Форм-фактор:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            пересувний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Захист від перевантаження DC/AC:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Клас ізоляції:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вага:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            42кг
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="gens__buy">
                            <MyButton2
                                btnHeight="140px"
                                fontSize={
                                    width < 312 ? 15 : width > 505 ? 30 : 18
                                }
                                lineHeight={width > 505 ? 40 : 20}
                            >
                                Замовити зі знижкою
                                <br />
                                LUOTIAN LT4500
                            </MyButton2>
                        </div>
                    </div>
                    <div className="gensList__item">
                        <div className="gens__title">
                            <div className="gens__title-value __container">
                                Газово-бензиновий генератор LUOTIAN LT6500
                            </div>
                        </div>
                        <div className="gens__picture __container">
                            <Image src={genImg3} alt="generator" />
                        </div>
                        <div className="gens__discount">
                            <Discount
                                lowPrice={9999}
                                price={9999}
                                percent={20}
                            />
                        </div>
                        <div className="gens__timer">
                            <Timer />
                        </div>
                        <div className="gens__text">
                            <div className="gens__text-value __container">
                                Це бензеновий генератор, який допоможе отримати
                                Вам додаткове джерело електроенергії для
                                використання у разі проблем із електромережею з
                                різною номінальною потужністю в залежності від
                                ваших потреб. Агрегат впорається з живленням
                                електроприладів для дому, офісу
                            </div>
                        </div>
                        <div className="gens__reference">
                            <div className="gens__reference-title" onClick={()=> setOpenLT6500(!openLT6500)}>
                                <div className="gens__reference-title-value">
                                    ХАРАКТЕРИСТИКИ
                                </div>
                                <div className="gens__reference-title-icon">
                                    <Image src={!openLT6500 ? referenceIcon : referenceIconUp} alt="icon" />
                                </div>
                            </div>
                            <div className="gens__reference-row ">
                                <div
                                    className="gens__reference-row-border-third __container"
                                    style={
                                        !openLT6500
                                            ? { height: "210px" }
                                            : { height: "" }
                                    }
                                >
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система пуску:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            кнопка
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Номінальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            6 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Максимальна потужність:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            6,5 кВт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Напруга:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220/12 В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            бензин / газ
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Об'єм паливного бака:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            15 л.
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Витрата палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            0,7-1 л/год{" "}
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Безперебійна праця без
                                            дозаправлення:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            15-20 годин
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Тип двигуна:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            {" "}
                                            4-тактний Одноциліндровий с
                                            повітряним охолодженням
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Розмір циліндра:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            88 х 64 мм
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість фаз:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            однофазний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Система AVR:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Кількість розеток:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            220 В: 2 шт
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик палива:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Датчик рівня масла:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вольтметр:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Форм-фактор:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            пересувний
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Захист від перевантаження DC/AC:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            так
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Клас ізоляції:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            В
                                        </div>
                                    </div>
                                    <div className="gens__reference-dashed"></div>
                                    <div className="gens__reference-keyValue">
                                        <div className="gens__reference-keyValue-key">
                                            Вага:
                                        </div>
                                        <div className="gens__reference-keyValue-value">
                                            84кг
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="gens__buy">
                            <MyButton2
                                btnHeight="140px"
                                fontSize={
                                    width < 312 ? 15 : width > 505 ? 30 : 18
                                }
                                lineHeight={width > 505 ? 40 : 20}
                            >
                                Замовити зі знижкою
                                <br />
                                LUOTIAN LT6500
                            </MyButton2>
                        </div>
                    </div>
                </section>
            </div>
        </>
    );
}
